# application.yml
spring:
  application:
    name: my-axon-spring-app
  datasource:
    url: jdbc:mysql://localhost:3306/cqrs
    username: root
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
axon:
  axonserver:
    enabled: true
    servers: localhost:8124
