---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: first-service 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-instance
          image: mysql:latest
          ports:
            - name: tcp
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates: 
    - metadata:
        name: mysql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: slow 
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql-service-port 
      port: 3306
      targetPort: 3306
  clusterIP: None 
